-- Using the five-step process, define the library functions that
--   calculate the 'sum' of a list of numbers
--   'take' a given number of elements from the start of a list
--   select the 'last' element of a non-empty list
